# Path variables
MY_PATH = /uscms/homes/j/joyzhou/work/hhbbtautau

# Job description
universe = vanilla
arguments = $(arg1)
executable = $(MY_PATH)/exec/run.sh
log = $(arg1).$(ProcId).log
output = $(arg1).$(ProcId).out
error = $(arg1).$(ProcId).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(MY_PATH)/src, $(MY_PATH)/setup.sh, $(MY_PATH)/lpcsetup.sh, $(MY_PATH)/scripts, $(MY_PATH)/dirsetup.sh, $(MY_PATH)/hhbbttrun.tar.gz
queue arg1 from (
    ggF
)

