universe = vanilla
executable = /uscms/homes/j/joyzhou/work/hhbbtautau/exec/run.sh
arguments = $(arg1)
log = $(arg1).$(ProcId).log
output = $(arg1).$(ProcId).out
error = $(arg1).$(ProcId).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /uscms/homes/j/joyzhou/work/hhbbtautau/src, /uscms/homes/j/joyzhou/work/hhbbtautau/setup.sh, /uscms/homes/j/joyzhou/work/hhbbtautau/lpcsetup.sh, /uscms/homes/j/joyzhou/work/hhbbtautau/scripts, /uscms/homes/j/joyzhou/work/hhbbtautau/dirsetup.sh
queue arg1 from (
    DYJets
)

