default:
  Tau:
    jetidx: Tau_jetIdx
    idvsjet: Tau_idDeepTau2017v2p1VSjet
    idvsmu: Tau_idDeepTau2017v2p1VSmu
    idvse: Tau_idDeepTau2017v2p1VSe
    charge: Tau_charge
    dxy: Tau_dxy
    dz: Tau_dz
  Electron:
    cbtightid: Electron_cutBased
    mvaisoid: Electron_mvaIso_WP90
  Muon:
    looseid: Muon_looseId
    mediumid: Muon_mediumId
    isoid04: Muon_pfRelIso04_all
    isoid: Muon_pfIsoId
    tightid: Muon_tightId
  Jet:
    btag: Jet_btagPNetB
    # btag: Jet_btagDeepFlavB
    jetid: Jet_jetId
    nconstituents: Jet_nConstituents



          
          
