# Creates name map for objects, used for creating n-tuples
default:
  Tau:
    charge: Tau_charge
    dxy: Tau_dxy
    dz: Tau_dz
    jetidx: Tau_jetIdx
    idvsjet: Tau_idDeepTau2018v2p5VSjet
    idvsmu: Tau_idDeepTau2018v2p5VSmu
    idvse: Tau_idDeepTau2018v2p5VSe
    genflav: Tau_genPartFlav
  Electron:
    cbtightid: Electron_cutBased
    mvaisoid: Electron_mvaIso_WP90
  Muon:
    looseid: Muon_looseId
    mediumid: Muon_mediumId
    tightid: Muon_tightId
    isoid04: Muon_pfRelIso04_all
    isoid: Muon_pfIsoId
  Jet:
    btag: Jet_btagPNetB
    # pnettau: Jet_btagPNetTauVJet
    jetid: Jet_jetId
    nconstituents: Jet_nConstituents
  GenPart:
    pdgid: GenPart_pdgId
    motherid: GenPart_genPartIdxMother
    charge: GenPart_charge
  GenVisTau:
    charge: GenVisTau_charge
    motherid: GenVisTau_genPartIdxMother



          
          
