# loose selections (of Tau)
default:
  name: "tauhtauh"
  triggerselections: 
    HLT_DoubleMediumDeepTauPFTauHPS35_L2NN_eta2p1: true
  objselections:
    Electron: 
      mvaIso_WP90: True
      pt: 40
      eta: 2.1
      dxy: 0.045
      dz: 0.2
      count: 0
    Muon: 
      pt: 40
      eta: 2.4
      dxy: 0.045
      dz: 0.2
      cbtightid: True
      isoid04: 0.3
      count: 0
    Tau:
      pt: 40
      eta: 2.5
      idvsjet: 2 # VVLoose
      idvsmu: 1 # V loose
      idvse: 2 # VV loose
      dz: 0.2
      count: 2
    Jet:
      pt: 20
      eta: 2.5
      btag: 0.0499 # pnet loose WP
      # pnetbtag: 0.0499 # loose WP
      count: 2
      jetid: 6
