[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim" # Data from processor
LOCALOUTPUT = "/uscms/home/joyzhou/nobackup/hadded"
CONDOR_TRANSFER = true 
CONDORPATH = "/store/user/joyzhou/hadded"
REFRESH = false # of now impact as of now
HADD_BATCH = 50
CLEANCSV = false
CLEANROOT = true
DATASETS = ['ZZ']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
LUMI = 5000 # pb^-1
RESOLUTION = 'process'


[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




