[LPCTEST]
DATAPATH = "@format {env[DATA_DIR]}/preprocessed"
INPUTDIR = "@format {env[CONDOR_BASE]}/lepskim"
LOCALOUTPUT = "/uscms/home/joyzhou/nobackup/hadded"
# DATASETS = ['DYJets', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
DATASETS = ['DYJets', 'WW', 'WWW', 'WZ', 'ZH', 'ZZ']
# DATASETS = ["ggF"]
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
RESOLUTION = 'process'
SIGNAL = 'ggF'
LUMI = 76.1 # fb^-1


[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




