[LPCTEST]
CONDORBASE = "/store/user/joyzhou" 
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "@format {this.CONDORBASE}/lepskim" # Data from processor
LOCALOUTPUT = "/uscms/home/joyzhou/nobackup/hadded"
CONDOR_TRANSFER = true
CONDORPATH = "/store/user/joyzhou/lepskim_hadded"
REFRESH = false # of now impact as of now
HADD_BATCH = 30
CLEANCSV = false
CLEANROOT = true
# DATASETS = ['DYJets', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
DATASETS = ['ggF']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
RESOLUTION = 'process'
SIGNAL = 'ggF'


[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




