[LPCJUPYTER]
CONDORBASE = "/store/user/joyzhou" 
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "@format {this.CONDORBASE}/hadded" # Data from processor
LOCALOUTPUT = "/uscms/home/joyzhou/nobackup/hadded"
CONDOR_TRANSFER = true 
CONDORPATH = "/store/user/joyzhou/hadded"
REFRESH = false # of now impact as of now
HADD_BATCH = 50
CLEANCSV = false
CLEANROOT = true
DATASETS = ['DYJets', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
LUMI = 73400 # pb^-1 to match xsection
RESOLUTION = 'process'


[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




