[LPCTEST]
SELNAME = 'prelim_looseb'
DATAPATH = "@format {env[DATA_DIR]}/preprocessed"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
DATASETS = ['DYJets', 'TTbar', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
# DATASETS = ['ZH', 'SingleH', 'ggF', "ZZ", "DYJets", "WWW", "WW"]
# DATASETS = ['ggF']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'LHEReweightingWeight']
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1

[LOCAL]
SELNAME = 'prelim_looseb'
DATAPATH = "@format {env[HHBBTT]}/src/data/preprocessed"
INPUTDIR = "@format {env[DATA_DIR]}/{this.SELNAME}/datasource"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.SELNAME}"
DATASETS = ['DYJets', 'TTbar', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
# DATASETS = ['ZH', 'SingleH', 'ggF', "ZZ", "DYJets", "WWW", "WW"]
# DATASETS = ['ggF']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'LHEReweightingWeight']
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1

