[LPCTEST]
SELNAME = 'prelim'
DATAPATH = "@format {env[DATA_DIR]}/preprocessed"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
DATASETS = ['DYJets', 'TTbar', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
# DATASETS = ['ZH', 'SingleH', 'ggF', "ZZ", "DYJets", "WWW", "WW"]
# DATASETS = ['DYJets']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 76.1 # fb^-1


[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




