default:
  size: 1
  signal:
    triggersel: 
      nFatJet: 1
      nJet: 2
    channelnames: ["taumtauh", "tauetauh", "tauhtauh"]
    channelno: 3
    channel1:
      name: "taumtauh"
      triggers:
        electron: null
        muon: ["HLT_Mu25_TkMu0_Onia","HLT_IsoMu20_eta2p1_TightChargedIsoPFTauHPS27_eta2p1_TightID_CrossL1"]
        tau: null
      selections:
        electron:
          veto: True
          pt: 25
        muon: 
          veto: False
          pt: 25
          eta: 2.1
          iso: 0.15
          count: 1
          dxy: 0.045
          dz: 0.2
        tau:
          veto: False
          pt: 35
          eta: 2.3
          idvsjet: 5
          idvsmu: 4
          idvse: 3
          dz: 0.2
          count: 1
        pair:
          name: "MT" 
          OS: True
          dRLevel: 0.5
    channel2:
      name: "tauetauh"
      triggers:
        electron: ["HLT_Ele24_eta2p1_WPTight_Gsf_TightChargedIsoPFTauHPS30_eta2p1_CrossL1","HLT_Ele32_WPTight_Gsf"]
        muon: null
        tau: null
      selections:
        electron:
          veto: False
          bdtid: 1
          pt: 33
          eta: 2.1
          dxy: 0.045
          dz: 0.2
          count: 1
        muon:
          veto: True
          pt: 25
        tau: 
          veto: False
          pt: 35
          eta: 2.3
          idvsmu: 4
          idvse: 3
          dz: 0.2
          count: 1
        pair:
          name: "ET"
          OS: True
          dRLevel: 0.5
    channel3:
      name: "tauhtauh"
      selections:
        electron: 
          veto: True
          pt: 25
        muon: 
          veto: True
          pt: 25
        tau:
          veto: False
          pt: 40
          eta: 2.3
          idvsjet: 5
          idvsmu: 1
          idvse: 2
          dz: 0.2
          count: 2
          OS: true
    commonsel:
      Jet:
        pt: 20
        eta: 2.4
        dRLevel: 0.5
        count: 2
        overlapCheck: True
      FatJet:
        mass: 40
        count: 1
    outputs:
      Tau:
        float: 
          pt: Tau_pt
          eta: Tau_eta
          phi: Tau_phi
          mass: Tau_mass
          dxy: Tau_dxy
          dz: Tau_dz
        int:
          charge: Tau_charge
        uint:
          idvsjet: Tau_idDeepTau2017v2p1VSjet
          idvsmu: Tau_idDeepTau2017v2p1VSmu
          idvse: Tau_idDeepTau2017v2p1VSe
      Electron:
        float:
          pt: Electron_pt
          eta: Electron_eta
          phi: Electron_phi
          mass: Electron_mass
          dxy: Electron_dxy
          dz: Electron_dz
          bdtid: Electron_tightCharge
        int:
          charge: Electron_charge
      Muon:
        float:
          pt: Muon_pt
          eta: Muon_eta
          phi: Muon_phi
          mass: Muon_mass
          dxy: Muon_dxy
          dz: Muon_dz
          iso: Muon_pfRelIso04_all
        bool:
          tightid: Muon_tightId
        int: 
          charge: Muon_charge
      Jet:
        float:
          pt: Jet_pt
          eta: Jet_eta
          phi: Jet_phi
          mass: Jet_mass
          deepJetbtagger: Jet_btagDeepFlavB
          deepJetCvsB: Jet_btagDeepFlavCvB
        uint:
          jetID: Jet_jetId
      FatJet:
        float:
          pt: FatJet_pt
          eta: FatJet_eta
          phi: FatJet_phi
          mass: FatJet_mass
        uint:
          jetID: FatJet_jetId



          
          
