[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
CONDORPATH = "/store/user/joyzhou/output"
INPUTDIR = "/uscms/home/joyzhou/nobackup/output"
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/plots"
CONDOR_TRANSFER = true # as of now this has zero impact
REFRESH = true
DATASETS = ["ggF", "SingleH", "DYJets", "TTbar"]
TREENAME = 'tree'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
CLEAN = true

[LPCCONDOR]
DATAPATH = "@format src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/jet_output"
CONDOR_TRANSFER = true
CONDORPATH = "/store/user/joyzhou/pkl_files"
OUTPUTDIR = "tempout"
DATASETS = ["ggF", "SingleH"]
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false




