[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
CONDORPATH = "/store/user/joyzhou/output"
INPUTDIR = "/uscms/home/joyzhou/nobackup/output"
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/plots"
CONDOR_TRANSFER = true
DATASETS = ["ZH", "SingleH", "ggF"]
TREENAME = 'tree'
PLOT_VARS = ['Tau', 'Jet', 'FatJet']
EXTRA_VARS = []

