[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
CONDORPATH = "/store/user/joyzhou/output"
INPUTDIR = "/uscms/home/joyzhou/nobackup/output"
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/plots"
CONDOR_TRANSFER = true
REFRESH = true
DATASETS = ["DYJets", "ZH", "SingleH", "ggF", "WJets", "WZ", "WZZ"]
TREENAME = 'tree'
PLOT_VARS = ['Tau', 'Jet', 'FatJet']
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
CLEAN = true

