[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim" # Data from processor
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/hadded"
CONDOR_TRANSFER = true 
CONDORPATH = "/store/user/joyzhou/hadded"
PLOTDATA = "/store/user/joyzhou/hadded" 
REFRESH = false # whether to hadd roots and csv
HADD_BATCH = 30
CLEAN = true
FROM_LOAD = true
DATASETS = ["WW", "ZH", "ggF"]
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
LUMI = 5000 # pb^-1

[LPCCONDOR]
DATAPATH = "src/data/preprocessed"
INPUTDIR = "/store/user/joyzhou/skim"
CONDORPATH = "/store/user/joyzhou/hadded"
OUTPUTDIR = "tempout"
CONDOR_TRANSFER = true
DATASETS = ["ggF"]
EXTRA_VARS = ['Generator_weight', 'nLHEReweightingWeight', 'LHEReweightingWeight']
TREENAME = "tree"
CLEAN = false
LUMI = 5000 # pb^-1




