[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "/uscms/home/joyzhou/nobackup/output"
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/plots"
CONDOR_TRANSFER = true
DATASETS = ["DYJets", "ZH", "SingleH"]
TREENAME = 'tree'
PLOT_VARS = ['Tau_pt', 'Tau_eta']

