[LPCJUPYTER]
DATAPATH = "/uscms/home/joyzhou/work/hhbbtautau/src/data/preprocessed"
INPUTDIR = "/uscms/home/joyzhou/nobackup/output"
OUTPUTDIR = "/uscms/home/joyzhou/nobackup/plots"
CONDOR_TRANSFER = true
DATASETS = ["DYJets", "ZH"]

