    channel1:
      name: "taumtauh"
      triggers:
        electron: null
        muon: ["HLT_Mu25_TkMu0_Onia","HLT_IsoMu20_eta2p1_TightChargedIsoPFTauHPS27_eta2p1_TightID_CrossL1"]
        tau: null
      selections:
        electron:
          veto: True
          pt: 25
        muon: 
          veto: False
          pt: 25
          eta: 2.1
          iso: 0.15
          count: 1
          dxy: 0.045
          dz: 0.2
        tau:
          veto: False
          pt: 35
          eta: 2.3
          idvsjet: 5
          idvsmu: 4
          idvse: 3
          dz: 0.2
          count: 1
        pair:
          name: "MT" 
          OS: True
          dRLevel: 0.5
    channel2:
      name: "tauetauh"
      triggers:
        electron: ["HLT_Ele24_eta2p1_WPTight_Gsf_TightChargedIsoPFTauHPS30_eta2p1_CrossL1","HLT_Ele32_WPTight_Gsf"]
        muon: null
        tau: null
      selections:
        electron:
          veto: False
          bdtid: 1
          pt: 33
          eta: 2.1
          dxy: 0.045
          dz: 0.2
          count: 1
        muon:
          veto: True
          pt: 25
        tau: 
          veto: False
          pt: 35
          eta: 2.3
          idvsmu: 4
          idvse: 3
          dz: 0.2
          count: 1
        pair:
          name: "ET"
          OS: True
          dRLevel: 0.5