default:
  name: "tauhtauh"
  triggerselections: 
    HLT_DoubleMediumDeepTauPFTauHPS35_L2NN_eta2p1: true
  objselections:
    GenPart: null
    Electron: 
      mvaisoid: True
      pt: 25
      eta: 2.1
      dxy: 0.045
      dz: 0.2
      count: 0
    Muon: 
      pt: 20
      eta: 2.1
      dxy: 0.045
      dz: 0.2
      looseid: true
      isoid: 1
      count: 0
    Tau:
      pt: 40
      eta: 2.3
      idvsjet: 5
      idvsmu: 1
      idvse: 2
      dz: 0.2
      count: 2
      OS: true
    Jet:
      pt: 20
      eta: 2.4
      btag: 0.0614 # loose WP
      # btag: 0.3196 # medium WP
      # pnetbtag: 0.0499 # loose WP
      count: 2
      jetid: 3
