[SKIM]
DIRNAME = 'vetoskim'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'root'

[PRESELECT]
DIRNAME = 'twob'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
SIGNAL = ['ggF']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'

[LOCAL]
DIRNAME = 'prelim_onelooseb'
DATAPATH = "@format {env[HHBBTT]}/data"
INPUTDIR = "@format {env[DATA_DIR]}/{this.DIRNAME}/datasource"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.DIRNAME}"
TREENAME = 'Events'
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'
