[SKIM]
DIRNAME = 'tightskim'
METADATA = "@format {env[DATA_DIR]}/availableMC" 
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
OUTTYPE = 'root'

[PRESELECT]
DIRNAME = 'tight_oneb_looseT'
METADATA = "@format {env[DATA_DIR]}/weightedMC" 
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
OUTTYPE = 'csv'

[LOCAL]
DIRNAME = 'postprocessed'
DATAPATH = "@format {env[HHBBTT]}/data"
METADATA = "@format {this.DATAPATH}/weightedMC" 
INPUTDIR = "@format {env[DATA_DIR]}/{this.DIRNAME}/oneb"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.DIRNAME}"
OUTTYPE = 'csv'
