[SKIM]
SELNAME = 'vetoskim'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.SELNAME}_hadded"
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'root'

[PRESELECT]
SELNAME = 'prelim'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.SELNAME}_hadded"
SIGNAL = ['ggF', 'TTbar']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'

[LOCAL]
SELNAME = 'prelim_onelooseb'
DATAPATH = "@format {env[HHBBTT]}/data"
INPUTDIR = "@format {env[DATA_DIR]}/{this.SELNAME}/datasource"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.SELNAME}"
TREENAME = 'Events'
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'

