[SKIM]
DIRNAME = 'tightskim'
METADATA = "@format {env[DATA_DIR]}/availableMC" 
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
OUTTYPE = 'root'

[PRESELECT]
DIRNAME = 'training_tightskim_looseT'
METADATA = "@format {env[DATA_DIR]}/availableMC" 
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.DIRNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.DIRNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.DIRNAME}_hadded"
OUTTYPE = 'csv'

[LOCAL]
DIRNAME = 'prelim_onelooseb'
METADATA = "@format {env[HHBBTT]}/data/availableMC" 
DATAPATH = "@format {env[HHBBTT]}/data"
INPUTDIR = "@format {env[DATA_DIR]}/{this.DIRNAME}/datasource"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.DIRNAME}"
OUTTYPE = 'csv'
