[SKIM]
SELNAME = 'vetoskim'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.SELNAME}_hadded"
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'root'

[PRESELECT]
SELNAME = 'RegionCD'
METADATA = "@format {env[DATA_DIR]}/availableQuery.json" 
NEWMETA = "@format {env[DATA_DIR]}/processedQuery.json"
INPUTDIR = "@format {env[CONDOR_BASE]}/{this.SELNAME}"
LOCALOUTPUT = "@format /uscms/home/joyzhou/nobackup/hadded/{this.SELNAME}"
TRANSFERPATH = "@format /store/user/joyzhou/{this.SELNAME}_hadded"
SIGNAL = ['ggF', 'TTbar']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'

[LOCAL]
SELNAME = 'prelim_onelooseb'
DATAPATH = "@format {env[HHBBTT]}/data"
INPUTDIR = "@format {env[DATA_DIR]}/{this.SELNAME}/datasource"
LOCALOUTPUT = "@format {env[DATA_DIR]}/{this.SELNAME}"
DATASETS = ['DYJets', 'TTbar', 'SingleH', 'WW', 'WWW', 'WZ', 'ZH', 'ggF', 'ZZ']
# DATASETS = ['ZH', 'SingleH', 'ggF', "ZZ", "DYJets", "WWW", "WW"]
# DATASETS = ['ggF']
TREENAME = 'Events'
PLOT_VARS = ['Tau', 'Jet', 'FatJet', "GenPart"]
EXTRA_VARS = ['Generator_weight', 'LHEReweightingWeight']
SIGNAL = ['ggF', 'ZH', 'ZZ']
LUMI = 220 # fb^-1
OUTTYPE = 'csv'

