[PRESELECT]
SEL_NAME = 'prelim_onelooseb'
JOB_PATH = 'skimmed'
DELAYED_OPEN = false
JOB_DIRNAME = 'preseljson'
TRANSFER_PATH = '/store/user/joyzhou/oneb'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]
OUTPUT_FORMAT = 'csv'

[SKIM]
SEL_NAME = 'vetoskim'
JOB_PATH = 'preprocessed'
# DELAYED_OPEN = true
JOB_DIRNAME = 'skimjson'
TRANSFER_PATH = '/store/user/joyzhou/vetoskim'
OUTPUT_FORMAT = 'root'

[LPCTEST]
SEL_NAME = 'vetoskim' 
# DELAYED_OPEN = false
OUTPUTDIR_PATH = "/uscms/home/joyzhou/nobackup/tests"
TRANSFER_PATH = '/store/user/joyzhou/tests'
COPY_DIR = "/uscms/home/joyzhou/nobackup/temp"
TEST_JSON = "/uscms/home/joyzhou/work/hhbbtautau/tests/testInputs/ggF_NANOAOD12.json"
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]