[PRESELECT]
SEL_NAME = 'prelim_twolooseb'
JOB_PATH = 'skimmed'
DELAYED_OPEN = false
JOB_DIRNAME = 'preseljson'
TRANSFER_PATH = '/store/user/joyzhou/twob_looseT'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]
OUTENDPATTERN = ["output.csv", "cutflow.csv"]

[SKIM]
SEL_NAME = 'tightskim'
JOB_PATH = 'preprocessed'
DELAYED_OPEN = false
REMOTE_LOAD = false
JOB_DIRNAME = 'skimjson'
TRANSFER_PATH = '/store/user/joyzhou/tightskim'
OUTENDPATTERN = [".root", "cutflow.csv"]

[LPCTEST]
SEL_NAME = 'vetoskim' 
# DELAYED_OPEN = false
OUTPUTDIR_PATH = "/uscms/home/joyzhou/nobackup/tests"
TRANSFER_PATH = '/store/user/joyzhou/tests'
COPY_DIR = "/uscms/home/joyzhou/nobackup/temp"
TEST_JSON = "/uscms/home/joyzhou/work/hhbbtautau/tests/testInputs/ggF_NANOAOD12.json"
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]