[ONEB]
SEL_NAME = 'onelooseb'
PROC_NAME = 'preselect'
DELAYED_OPEN = false
TRANSFER_PATH = '/store/user/joyzhou/tightskim_onelooseb'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]
OUTENDPATTERN = ["output.csv", "cutflow.csv"]
JOB_DIR = 'tightskimmed'

[TWOB]
SEL_NAME = 'twolooseb'
PROC_NAME = 'preselect'
DELAYED_OPEN = false
TRANSFER_PATH = '/store/user/joyzhou/tightskim_twolooseb'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]
OUTENDPATTERN = ["output.csv", "cutflow.csv"]
JOB_DIR = 'tightskimmed'

[NOB]
SEL_NAME = 'zerolooseb'
PROC_NAME = 'preselect'
DELAYED_OPEN = false
TRANSFER_PATH = '/store/user/joyzhou/zerolooseb'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*"]
OUTENDPATTERN = ["output.csv", "cutflow.csv"]
JOB_DIR = 'skimmed'

[SKIM]
SEL_NAME = 'vbfskim'
PROC_NAME = 'skim'
TRANSFER_PATH = '/store/user/joyzhou/vbfskim'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*", "HLT*", "MET"]
OUTENDPATTERN = [".root", "cutflow.csv"]
JOB_DIR = 'preprocessed'

[TIGHTSKIM]
SEL_NAME = 'tightskim'
PROC_NAME = 'skim'
TRANSFER_PATH = '/store/user/joyzhou/tightskim'
FILTER_NAME = ["Tau*", "Jet*", "Electron*", "Muon*", "Gen*", "LHE*", "HLT*", "MET"]
OUTENDPATTERN = [".root", "cutflow.csv"]
JOB_DIR = 'preprocessed'